export const MAGIC_NUMBER = 0x53594D50 // "SYMP" in ASCII
export const NULL = 0

export const OK = 0
export const ERROR_NONE = 0
export const ERROR_MAGIC_MISMATCH = 1 << 0
export const ERROR_VERSION_MISMATCH = 1 << 1
export const ERROR_INIT_FAILURE = 1 << 2

export const ERROR_FREE_LIST_CORRUPT = 1 << 3

export const ERROR_HEAP_EXHAUSTED = 1 << 4
export const ERROR_DOUBLE_FREE = 1 << 5
export const ERROR_OUT_OF_BOUNDS = 1 << 6
export const ERROR_ALIGNMENT_VIOLATION = 1 << 7
export const ERROR_RING_BUFFER_OVERFLOW = 1 << 8
export const ERROR_CONTENTION_EXCEEDED = 1 << 9

export const ERROR_RING_BUFFER_EMPTY = 1 << 10
export const ERROR_BUFFER_SIZE_MISMATCH = 1 << 11

export const ERROR_KERNEL_PANIC =
  ERROR_MAGIC_MISMATCH
  | ERROR_VERSION_MISMATCH
  | ERROR_INIT_FAILURE

export const ERROR_ZONE_PANIC = ERROR_FREE_LIST_CORRUPT

export const ERROR_ZONE_RECOVERABLE =
  ERROR_HEAP_EXHAUSTED
  | ERROR_DOUBLE_FREE
  | ERROR_OUT_OF_BOUNDS
  | ERROR_ALIGNMENT_VIOLATION
  | ERROR_RING_BUFFER_OVERFLOW
  | ERROR_CONTENTION_EXCEEDED
  | ERROR_RING_BUFFER_EMPTY
  | ERROR_BUFFER_SIZE_MISMATCH
